import type {
  PortalBorrowRequest,
  PortalBorrowLogRecord,
  BrowseItem,
  PortalSummaryStats,
} from "./types";

// ─── Current User ─────────────────────────────────────────────────────────────
export const CURRENT_USER = {
  name: "Maria Santos",
  email: "m.santos@aims.org",
  department: "IT",
};

// ─── Browse Items ─────────────────────────────────────────────────────────────
export const BROWSE_ITEMS: BrowseItem[] = [
  {
    type: "asset",
    id: "a-001",
    name: "Dell Latitude 5420 Laptop",
    category: "computing",
    status: "active",
    assetCode: "CP-080",
    location: "IT Equipment Room",
    notes: "Includes charger. Pre-installed with MS Office and VPN client.",
  },
  {
    type: "asset",
    id: "a-002",
    name: "Epson PowerLite LCD Projector",
    category: "av",
    status: "active",
    assetCode: "AV-014",
    location: "AV Cabinet, Room 201",
    notes: "Supports HDMI and VGA. Max resolution 1080p.",
  },
  {
    type: "asset",
    id: "a-003",
    name: "Ergonomic Mesh Office Chair",
    category: "furniture",
    status: "active",
    assetCode: "FN-045",
    location: "Storage Room B",
  },
  {
    type: "asset",
    id: "a-004",
    name: "Toyota Coaster Utility Van",
    category: "transport",
    status: "active",
    assetCode: "TR-004",
    location: "Campus Parking Area",
    notes: "Requires at least 2 days advance notice.",
  },
  {
    type: "asset",
    id: "a-005",
    name: "Canon EOS 90D DSLR Camera Kit",
    category: "av",
    status: "active",
    assetCode: "AV-031",
    location: "Media Center",
    notes: "Includes 2 lenses, flash, and 4 batteries.",
  },
  {
    type: "asset",
    id: "a-006",
    name: "Portable Wireless PA System",
    category: "av",
    status: "active",
    assetCode: "AV-008",
    location: "Events Storage",
    notes: "Battery-operated. Includes 2 wireless mics.",
  },
  {
    type: "asset",
    id: "a-007",
    name: "MacBook Pro 16\" Workstation",
    category: "computing",
    status: "needs_repair",
    assetCode: "CP-012",
    location: "IT Repair Bench",
    unavailableReason: "Currently under repair — fan replacement scheduled.",
  },
  {
    type: "asset",
    id: "a-008",
    name: "Executive Folding Conference Table",
    category: "furniture",
    status: "active",
    assetCode: "FN-012",
    location: "Conference Room A",
  },
  {
    type: "asset",
    id: "a-009",
    name: "HP LaserJet Pro Printer (Network)",
    category: "computing",
    status: "out_of_service",
    assetCode: "CP-055",
    location: "Admin Office",
    unavailableReason: "Out of service — awaiting parts from supplier.",
  },
  {
    type: "consumable",
    id: "c-001",
    name: "A4 Bond Paper (Ream)",
    category: "paper",
    status: "available",
    itemCode: "CON-001",
    unit: "ream",
    currentQty: 48,
    location: "Supply Room 1",
  },
  {
    type: "consumable",
    id: "c-002",
    name: "HP 651A Black Toner Cartridge",
    category: "ink_toner",
    status: "low_stock",
    itemCode: "CON-015",
    unit: "cartridge",
    currentQty: 3,
    location: "IT Supplies Cabinet",
    notes: "Compatible with HP LaserJet M604/M605/M606.",
  },
  {
    type: "consumable",
    id: "c-003",
    name: "Alcohol-based Hand Sanitizer 500ml",
    category: "medical",
    status: "available",
    itemCode: "CON-032",
    unit: "bottle",
    currentQty: 24,
    location: "Clinic Supplies",
  },
];

// ─── My Requests (scoped to CURRENT_USER) ────────────────────────────────────
export const INITIAL_MY_REQUESTS: PortalBorrowRequest[] = [
  {
    id: "pr-001",
    requestCode: "REQ-2026-0081",
    requesterName: CURRENT_USER.name,
    requesterEmail: CURRENT_USER.email,
    requesterPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    itemDescription: "Dell Latitude 5420 Laptop",
    assetCode: "CP-080",
    category: "computing",
    quantity: 1,
    purpose: "Off-site technical training seminar for regional IT staff.",
    requestedAt: "2026-08-07T08:30:00Z",
    expectedReturnDate: "2026-08-14",
    status: "pending",
    notes: "Requires pre-installed VPN and development software tools.",
    requestedDateFrom: "2026-08-08",
    requestedDateTo: "2026-08-14",
    itemType: "asset",
    history: [
      {
        id: "h-pr-1",
        action: "submitted",
        actor: CURRENT_USER.name,
        timestamp: "2026-08-07 08:30 AM",
        note: "Request submitted via Borrower Portal",
      },
    ],
  },
  {
    id: "pr-002",
    requestCode: "REQ-2026-0075",
    requesterName: CURRENT_USER.name,
    requesterEmail: CURRENT_USER.email,
    requesterPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    itemDescription: "Canon EOS 90D DSLR Camera Kit",
    assetCode: "AV-031",
    category: "av",
    quantity: 1,
    purpose: "Documentation of IT infrastructure upgrade project.",
    requestedAt: "2026-08-05T10:00:00Z",
    expectedReturnDate: "2026-08-07",
    status: "approved",
    releasedStatus: "waiting_pickup",
    requestedDateFrom: "2026-08-06",
    requestedDateTo: "2026-08-07",
    itemType: "asset",
    history: [
      {
        id: "h-pr-2a",
        action: "submitted",
        actor: CURRENT_USER.name,
        timestamp: "2026-08-05 10:00 AM",
      },
      {
        id: "h-pr-2b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-08-05 11:30 AM",
        note: "Approved for project documentation.",
      },
    ],
  },
  {
    id: "pr-003",
    requestCode: "REQ-2026-0068",
    requesterName: CURRENT_USER.name,
    requesterEmail: CURRENT_USER.email,
    requesterPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    itemDescription: "Portable Wireless PA System",
    assetCode: "AV-008",
    category: "av",
    quantity: 1,
    purpose: "IT Department townhall presentation.",
    requestedAt: "2026-07-28T09:00:00Z",
    expectedReturnDate: "2026-07-28",
    status: "rejected",
    rejectionReason:
      "Item already reserved for the HR Department onboarding event on the same date. Please choose a different date.",
    requestedDateFrom: "2026-07-28",
    requestedDateTo: "2026-07-28",
    itemType: "asset",
    history: [
      {
        id: "h-pr-3a",
        action: "submitted",
        actor: CURRENT_USER.name,
        timestamp: "2026-07-28 09:00 AM",
      },
      {
        id: "h-pr-3b",
        action: "rejected",
        actor: "Property Custodian",
        timestamp: "2026-07-28 09:45 AM",
        note: "Item already reserved for the HR Department onboarding event on the same date.",
      },
    ],
  },
  {
    id: "pr-004",
    requestCode: "REQ-2026-0055",
    requesterName: CURRENT_USER.name,
    requesterEmail: CURRENT_USER.email,
    requesterPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    itemDescription: "Epson PowerLite LCD Projector",
    assetCode: "AV-014",
    category: "av",
    quantity: 1,
    purpose: "End-of-quarter IT review presentation.",
    requestedAt: "2026-07-15T14:00:00Z",
    expectedReturnDate: "2026-07-15",
    status: "returned",
    requestedDateFrom: "2026-07-15",
    requestedDateTo: "2026-07-15",
    itemType: "asset",
    history: [
      {
        id: "h-pr-4a",
        action: "submitted",
        actor: CURRENT_USER.name,
        timestamp: "2026-07-15 02:00 PM",
      },
      {
        id: "h-pr-4b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-07-15 02:30 PM",
      },
      {
        id: "h-pr-4c",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-07-15 06:00 PM",
        note: "Returned in good condition.",
      },
    ],
  },
  {
    id: "pr-005",
    requestCode: "REQ-2026-0048",
    requesterName: CURRENT_USER.name,
    requesterEmail: CURRENT_USER.email,
    requesterPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    itemDescription: "A4 Bond Paper (Ream)",
    assetCode: undefined,
    category: "computing",
    quantity: 5,
    purpose: "Printing of IT audit documentation for Q2.",
    requestedAt: "2026-07-10T08:00:00Z",
    expectedReturnDate: "2026-07-10",
    status: "returned",
    requestedDateFrom: "2026-07-10",
    requestedDateTo: "2026-07-10",
    itemType: "consumable",
    requestedQuantity: 5,
    history: [
      {
        id: "h-pr-5a",
        action: "submitted",
        actor: CURRENT_USER.name,
        timestamp: "2026-07-10 08:00 AM",
      },
      {
        id: "h-pr-5b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-07-10 08:30 AM",
      },
      {
        id: "h-pr-5c",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-07-10 05:00 PM",
        note: "Consumable checkout completed.",
      },
    ],
  },
];

// ─── My Borrow History ────────────────────────────────────────────────────────
export const MY_BORROW_HISTORY: PortalBorrowLogRecord[] = [
  {
    id: "bl-001",
    logCode: "LOG-2026-0142",
    requestCode: "REQ-2026-0075",
    borrowerName: CURRENT_USER.name,
    borrowerEmail: CURRENT_USER.email,
    borrowerPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    assetCode: "AV-031",
    assetName: "Canon EOS 90D DSLR Camera Kit",
    category: "av",
    releasedAt: "2026-08-06T08:00:00Z",
    dueDate: "2026-08-07",
    status: "active",
    releasedBy: "Property Custodian",
    history: [
      {
        id: "bl-h1",
        action: "released",
        actor: "Property Custodian",
        timestamp: "2026-08-06 08:00 AM",
      },
    ],
  },
  {
    id: "bl-002",
    logCode: "LOG-2026-0138",
    requestCode: "REQ-2026-0065",
    borrowerName: CURRENT_USER.name,
    borrowerEmail: CURRENT_USER.email,
    borrowerPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    assetCode: "CP-080",
    assetName: "Dell Latitude 5420 Laptop",
    category: "computing",
    releasedAt: "2026-07-28T07:30:00Z",
    dueDate: "2026-07-30",
    daysOverdue: 8,
    status: "overdue",
    releasedBy: "Property Custodian",
    history: [
      {
        id: "bl-h2",
        action: "released",
        actor: "Property Custodian",
        timestamp: "2026-07-28 07:30 AM",
      },
      {
        id: "bl-h2b",
        action: "reminder_sent",
        actor: "System",
        timestamp: "2026-07-31 08:00 AM",
        notes: "Automated overdue reminder sent.",
      },
    ],
  },
  {
    id: "bl-003",
    logCode: "LOG-2026-0120",
    requestCode: "REQ-2026-0055",
    borrowerName: CURRENT_USER.name,
    borrowerEmail: CURRENT_USER.email,
    borrowerPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    assetCode: "AV-014",
    assetName: "Epson PowerLite LCD Projector",
    category: "av",
    releasedAt: "2026-07-15T14:30:00Z",
    dueDate: "2026-07-15",
    returnedAt: "2026-07-15T18:00:00Z",
    status: "returned",
    conditionOnReturn: "good",
    conditionNotes: "Returned in excellent condition. All accessories accounted for.",
    releasedBy: "Property Custodian",
    receivedBy: "Property Custodian",
    history: [
      {
        id: "bl-h3a",
        action: "released",
        actor: "Property Custodian",
        timestamp: "2026-07-15 02:30 PM",
      },
      {
        id: "bl-h3b",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-07-15 06:00 PM",
      },
    ],
  },
  {
    id: "bl-004",
    logCode: "LOG-2026-0098",
    requestCode: "REQ-2026-0040",
    borrowerName: CURRENT_USER.name,
    borrowerEmail: CURRENT_USER.email,
    borrowerPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    assetCode: "FN-045",
    assetName: "Ergonomic Mesh Office Chair",
    category: "furniture",
    releasedAt: "2026-06-20T09:00:00Z",
    dueDate: "2026-06-27",
    returnedAt: "2026-06-27T17:00:00Z",
    status: "returned",
    conditionOnReturn: "needs_repair",
    conditionNotes: "Armrest screw loose on right side. Flagged for maintenance.",
    releasedBy: "Property Custodian",
    receivedBy: "Property Custodian",
    history: [
      {
        id: "bl-h4a",
        action: "released",
        actor: "Property Custodian",
        timestamp: "2026-06-20 09:00 AM",
      },
      {
        id: "bl-h4b",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-06-27 05:00 PM",
      },
      {
        id: "bl-h4c",
        action: "flagged_repair",
        actor: "Property Custodian",
        timestamp: "2026-06-27 05:15 PM",
        notes: "Flagged for maintenance — armrest repair needed.",
      },
    ],
  },
  {
    id: "bl-005",
    logCode: "LOG-2026-0071",
    requestCode: "REQ-2026-0028",
    borrowerName: CURRENT_USER.name,
    borrowerEmail: CURRENT_USER.email,
    borrowerPhone: "+63 917 555 0192",
    department: CURRENT_USER.department,
    assetCode: "AV-031",
    assetName: "Canon EOS 90D DSLR Camera Kit",
    category: "av",
    releasedAt: "2026-05-10T08:00:00Z",
    dueDate: "2026-05-12",
    returnedAt: "2026-05-12T16:00:00Z",
    status: "returned",
    conditionOnReturn: "good",
    conditionNotes: "All components returned. Battery fully charged.",
    releasedBy: "Property Custodian",
    receivedBy: "Property Custodian",
    history: [
      {
        id: "bl-h5a",
        action: "released",
        actor: "Property Custodian",
        timestamp: "2026-05-10 08:00 AM",
      },
      {
        id: "bl-h5b",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-05-12 04:00 PM",
      },
    ],
  },
];

// ─── Summary Stats ────────────────────────────────────────────────────────────
export const SUMMARY_STATS: PortalSummaryStats = {
  activeBorrowings: MY_BORROW_HISTORY.filter((r) => r.status === "active" || r.status === "overdue").length,
  pendingRequests: INITIAL_MY_REQUESTS.filter((r) => r.status === "pending").length,
  overdueItems: MY_BORROW_HISTORY.filter((r) => r.status === "overdue").length,
  completedThisSemester: MY_BORROW_HISTORY.filter((r) => r.status === "returned").length,
};
