-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_code text NOT NULL UNIQUE,
  name text NOT NULL,
  category USER - DEFINED NOT NULL,
  status USER - DEFINED NOT NULL DEFAULT 'active'::asset_status,
  serial_number text,
  location text NOT NULL,
  current_holder text,
  department text,
  purchase_date date,
  value numeric,
  image_url text,
  notes text,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  maintenance_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  assignment_type USER - DEFINED NOT NULL DEFAULT 'borrowable'::asset_assignment_type,
  supplier_id uuid,
  CONSTRAINT assets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  type text NOT NULL DEFAULT 'asset'::text,
  color_token text,
  created_by_user_id uuid,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_created_by_user_id_profiles_user_id_fk FOREIGN KEY (created_by_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.asset_lifecycle_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid,
  asset_code text NOT NULL,
  event_type USER - DEFINED NOT NULL,
  actor_user_id uuid NOT NULL,
  actor_email text,
  actor_display_name text NOT NULL,
  from_status text,
  to_status text,
  from_holder text,
  to_holder text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_lifecycle_events_pkey PRIMARY KEY (id),
  CONSTRAINT asset_lifecycle_events_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role USER - DEFINED NOT NULL DEFAULT 'staff'::app_role,
  status USER - DEFINED NOT NULL DEFAULT 'active'::profile_status,
  department text,
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_active_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.borrow_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_code text NOT NULL UNIQUE,
  requester_user_id uuid,
  requester_name text NOT NULL,
  requester_email text NOT NULL,
  requester_phone text NOT NULL DEFAULT ''::text,
  department text NOT NULL,
  item_description text NOT NULL,
  asset_id uuid,
  asset_code text,
  category USER - DEFINED NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  purpose text NOT NULL,
  expected_return_date date NOT NULL,
  status USER - DEFINED NOT NULL DEFAULT 'pending'::borrow_request_status,
  notes text,
  rejection_reason text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  picked_up_by text,
  CONSTRAINT borrow_requests_pkey PRIMARY KEY (id),
  CONSTRAINT borrow_requests_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.borrow_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  log_code text NOT NULL UNIQUE,
  request_id uuid,
  request_code text,
  asset_id uuid,
  asset_code text NOT NULL,
  asset_name text NOT NULL,
  category USER - DEFINED NOT NULL,
  borrower_user_id uuid,
  borrower_name text NOT NULL,
  borrower_email text NOT NULL DEFAULT ''::text,
  borrower_phone text NOT NULL DEFAULT ''::text,
  department text NOT NULL,
  released_at timestamp with time zone NOT NULL DEFAULT now(),
  due_date date NOT NULL,
  returned_at timestamp with time zone,
  status USER - DEFINED NOT NULL DEFAULT 'active'::borrow_transaction_status,
  condition_on_return USER - DEFINED,
  condition_notes text,
  released_by_user_id uuid NOT NULL,
  released_by_name text NOT NULL,
  received_by_user_id uuid,
  received_by_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT borrow_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT borrow_transactions_request_id_borrow_requests_id_fk FOREIGN KEY (request_id) REFERENCES public.borrow_requests(id),
  CONSTRAINT borrow_transactions_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.consumables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_code text NOT NULL UNIQUE,
  name text NOT NULL,
  category USER - DEFINED NOT NULL,
  unit text NOT NULL,
  current_qty integer NOT NULL DEFAULT 0,
  min_threshold integer NOT NULL DEFAULT 0,
  location text NOT NULL,
  supplier text,
  last_restocked timestamp with time zone,
  notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consumables_pkey PRIMARY KEY (id)
);
CREATE TABLE public.maintenance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  log_code text NOT NULL UNIQUE,
  asset_id uuid,
  asset_code text NOT NULL,
  asset_name text NOT NULL,
  category USER - DEFINED NOT NULL,
  condition USER - DEFINED NOT NULL,
  source USER - DEFINED NOT NULL DEFAULT 'manual_flag'::maintenance_source,
  date_logged date NOT NULL,
  logged_by_user_id uuid NOT NULL,
  logged_by_name text NOT NULL,
  notes text NOT NULL DEFAULT ''::text,
  is_resolved boolean NOT NULL DEFAULT false,
  resolution_date date,
  resolution_notes text,
  resolved_by_user_id uuid,
  resolved_by_name text,
  related_borrow_log_code text,
  scheduled_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT maintenance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_logs_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  action text NOT NULL,
  actor_name text NOT NULL,
  actor_user_id uuid,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  metadata jsonb,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  status USER - DEFINED NOT NULL DEFAULT 'active'::project_status,
  location text,
  department text,
  start_date date,
  end_date date,
  budget numeric,
  notes text,
  created_by_user_id uuid NOT NULL,
  created_by_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_code text NOT NULL UNIQUE,
  name text NOT NULL,
  contact_name text,
  contact_email text,
  contact_phone text,
  address text,
  notes text,
  status USER - DEFINED NOT NULL DEFAULT 'active'::supplier_status,
  created_by_user_id uuid NOT NULL,
  created_by_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.purchase_lots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lot_code text NOT NULL UNIQUE,
  item_type USER - DEFINED NOT NULL,
  consumable_id uuid,
  asset_id uuid,
  item_code text NOT NULL,
  item_name text NOT NULL,
  supplier_id uuid,
  supplier_name text,
  quantity integer NOT NULL,
  quantity_remaining integer NOT NULL,
  unit_cost numeric NOT NULL,
  total_cost numeric NOT NULL,
  purchased_on date NOT NULL,
  reference text,
  notes text,
  recorded_by_user_id uuid NOT NULL,
  recorded_by_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_lots_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_lots_consumable_id_consumables_id_fk FOREIGN KEY (consumable_id) REFERENCES public.consumables(id),
  CONSTRAINT purchase_lots_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT purchase_lots_supplier_id_suppliers_id_fk FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.project_expense_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  line_type USER - DEFINED NOT NULL DEFAULT 'miscellaneous'::project_expense_line_type,
  category USER - DEFINED NOT NULL DEFAULT 'miscellaneous'::project_expense_category,
  description text NOT NULL,
  amount numeric NOT NULL,
  quantity numeric,
  unit_cost numeric,
  consumable_id uuid,
  asset_id uuid,
  incurred_on date NOT NULL,
  notes text,
  recorded_by_user_id uuid NOT NULL,
  recorded_by_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT project_expense_lines_pkey PRIMARY KEY (id),
  CONSTRAINT project_expense_lines_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_asset_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  asset_id uuid NOT NULL,
  asset_code text NOT NULL,
  asset_name text NOT NULL,
  status USER - DEFINED NOT NULL DEFAULT 'assigned'::project_asset_assignment_status,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  returned_at timestamp with time zone,
  assigned_by_user_id uuid NOT NULL,
  assigned_by_name text NOT NULL,
  returned_by_user_id uuid,
  returned_by_name text,
  notes text,
  return_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_asset_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT project_asset_assignments_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_asset_assignments_asset_id_assets_id_fk FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);