import type { MaintenanceLogRecord } from "./types";

export const INITIAL_MOCK_MAINTENANCE_LOGS: MaintenanceLogRecord[] = [
  {
    id: "mnt-001",
    logCode: "MNT-2026-0041",
    assetCode: "AV-031",
    assetName: "Canon EOS 90D DSLR Camera Kit",
    category: "av",
    condition: "needs_maintenance",
    source: "manual_flag",
    dateLogged: "2026-07-25",
    loggedBy: "Ben Aquino",
    notes: "Lens autofocus gear ring sticking intermittently during zoom tracking.",
    isResolved: false,
    scheduledDate: "2026-07-30",
  },
  {
    id: "mnt-002",
    logCode: "MNT-2026-0038",
    assetCode: "FN-012",
    assetName: "Modular Executive Conference Table",
    category: "furniture",
    condition: "damaged",
    source: "manual_flag",
    dateLogged: "2026-07-15",
    loggedBy: "Carpentry Team",
    notes: "Corner latch hinge pin bent during room relocation. Requires replacement bracket.",
    isResolved: false,
    scheduledDate: "2026-08-01",
  },
  {
    id: "mnt-003",
    logCode: "MNT-2026-0035",
    assetCode: "FN-045",
    assetName: "Ergonomic Mesh High-Back Office Chair",
    category: "furniture",
    condition: "needs_maintenance",
    source: "return_checkout",
    dateLogged: "2026-07-02",
    loggedBy: "Dave Custodio",
    notes: "Gas lift height cylinder slipping under weight after return check-in.",
    isResolved: false,
    relatedBorrowLogCode: "LOG-2026-0022",
  },
  {
    id: "mnt-004",
    logCode: "MNT-2026-0028",
    assetCode: "CP-080",
    assetName: "Dell Latitude 5420 Laptop",
    category: "computing",
    condition: "resolved",
    source: "manual_flag",
    dateLogged: "2025-11-10",
    loggedBy: "Dave Custodio",
    notes: "Annual hardware diagnostics & RAM check.",
    isResolved: true,
    resolutionDate: "2025-11-12",
    resolutionNotes: "Replaced 8GB RAM module with 16GB dual-channel stick. Passed 24h stress test.",
    resolvedBy: "IT Helpdesk",
  },
  {
    id: "mnt-005",
    logCode: "MNT-2026-0020",
    assetCode: "TR-004",
    assetName: "Toyota Coaster Utility Van",
    category: "transport",
    condition: "resolved",
    source: "manual_flag",
    dateLogged: "2026-06-01",
    loggedBy: "Central Garage",
    notes: "50,000 km periodic engine oil change & tire rotation.",
    isResolved: true,
    resolutionDate: "2026-06-02",
    resolutionNotes: "Oil filter replaced, fluid levels topped off, 4-wheel alignment performed.",
    resolvedBy: "Master Mechanic Garcia",
  },
  {
    id: "mnt-006",
    logCode: "MNT-2026-0015",
    assetCode: "AV-014",
    assetName: "Epson PowerLite LCD Projector #A-102",
    category: "av",
    condition: "resolved",
    source: "manual_flag",
    dateLogged: "2025-09-15",
    loggedBy: "AV Tech",
    notes: "Air filter cleaning & lamp runtime reset.",
    isResolved: true,
    resolutionDate: "2025-09-15",
    resolutionNotes: "Filter vacuumed clean, lamp counter reset to 0h.",
    resolvedBy: "AV Tech",
  },
];
