"use client";

import { Download, ShieldCheck, UserCheck, Calendar, User } from "lucide-react";
import type { SimpleUserRole } from "./types";

interface ReportsHeaderProps {
  generatedAt: string;
  generatedBy: string;
  roleView: SimpleUserRole;
  onRoleChange: (role: SimpleUserRole) => void;
  onExportClick: () => void;
}

const ROLE_LABELS: Record<SimpleUserRole, { title: string; badge: string }> = {
  staff: { title: "Staff Member", badge: "STAFF VIEW" },
  dept_head: { title: "Department Head", badge: "DEPARTMENT VIEW" },
  admin: { title: "System Administrator", badge: "FULL ACCESS" },
};

export function ReportsHeader({
  generatedAt,
  generatedBy,
  roleView,
  onRoleChange,
  onExportClick,
}: ReportsHeaderProps) {
  return (
    <div className="flex flex-col gap-4 bg-card border-b border-border px-4 py-5 md:px-6 shrink-0">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5">
            <h1 className="text-xl font-bold tracking-tight text-text">
              Reports & Inventory Analytics
            </h1>
            <span className="inline-flex items-center gap-1 rounded-full bg-status-active-bg/15 px-2.5 py-0.5 text-xs font-bold text-status-active-text border border-status-active-bg/30">
              <ShieldCheck className="h-3.5 w-3.5" />
              Real-time Analytics
            </span>
          </div>
          <p className="mt-1 text-xs text-text-secondary">
            Generate and export equipment valuation ledgers, borrowing logs, maintenance compliance, and disposal audit reports.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2.5">
          {/* Role View Selector */}
          <div className="flex items-center gap-1.5 bg-bg-subtle px-3 py-1.5 rounded-lg border border-border">
            <User className="h-4 w-4 text-text-secondary" />
            <span className="text-xs font-semibold text-text-secondary">Role:</span>
            <select
              value={roleView}
              onChange={(e) => onRoleChange(e.target.value as SimpleUserRole)}
              className="bg-transparent text-xs font-bold text-text focus:outline-none cursor-pointer"
            >
              <option value="admin">System Administrator</option>
              <option value="dept_head">Department Head</option>
              <option value="staff">Staff Member</option>
            </select>
          </div>

          {/* Export Action Button */}
          <button
            type="button"
            onClick={onExportClick}
            className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3.5 py-2 text-xs font-bold text-primary-foreground shadow-xs hover:opacity-90 transition-opacity cursor-pointer"
          >
            <Download className="h-4 w-4" />
            Export Report
          </button>
        </div>
      </div>

      {/* Audit Metadata Sub-bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-text-secondary border-t border-border pt-3">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1.5">
            <Calendar className="h-3.5 w-3.5 text-text-secondary/70" />
            <span>Timestamp: <strong className="font-mono text-text">{generatedAt}</strong></span>
          </span>
          <span className="flex items-center gap-1.5">
            <UserCheck className="h-3.5 w-3.5 text-text-secondary/70" />
            <span>Generated by: <strong className="text-text">{generatedBy}</strong></span>
          </span>
        </div>

        <div className="flex items-center gap-2">
          <span className="font-mono text-[11px] uppercase tracking-wider bg-bg-subtle px-2 py-0.5 rounded border border-border text-text font-bold">
            {ROLE_LABELS[roleView].badge}
          </span>
        </div>
      </div>
    </div>
  );
}
