import type { UserAccount } from "./types";

export const CURRENT_USER_ID = "usr-001"; // Currently logged-in Property Custodian Admin

export const INITIAL_MOCK_USERS: UserAccount[] = [
  {
    id: "usr-001",
    name: "Dave Custodio",
    email: "d.custodio@crmc.gov.ph",
    role: "admin",
    status: "active",
    department: "Property Custodian Office",
    dateAdded: "2024-01-15",
    lastActive: "Active now",
    activitySummary: "Processed 12 releases & 8 approvals this week",
  },
  {
    id: "usr-002",
    name: "Maria Santos",
    email: "m.santos@crmc.gov.ph",
    role: "staff",
    status: "active",
    department: "IT Services",
    dateAdded: "2024-03-10",
    lastActive: "2 hours ago",
    activitySummary: "Checked out 2 computing assets yesterday",
  },
  {
    id: "usr-003",
    name: "Juan dela Cruz",
    email: "j.delacruz@crmc.gov.ph",
    role: "staff",
    status: "active",
    department: "Finance",
    dateAdded: "2024-05-20",
    lastActive: "Yesterday at 4:15 PM",
    activitySummary: "Submitted 1 borrow request this month",
  },
  {
    id: "usr-004",
    name: "Rosa Reyes",
    email: "r.reyes@crmc.gov.ph",
    role: "viewer",
    status: "active",
    department: "HR & Onboarding",
    dateAdded: "2024-06-01",
    lastActive: "3 days ago",
    activitySummary: "Viewed asset inventory reports",
  },
  {
    id: "usr-005",
    name: "Ben Aquino",
    email: "b.aquino@crmc.gov.ph",
    role: "staff",
    status: "active",
    department: "Communications",
    dateAdded: "2024-07-12",
    lastActive: "Jul 26, 2026",
    activitySummary: "Flagged 1 AV asset for repair",
  },
  {
    id: "usr-006",
    name: "Dr. Gabriel Soriano",
    email: "g.soriano@crmc.gov.ph",
    role: "viewer",
    status: "deactivated",
    department: "Executive Committee",
    dateAdded: "2023-11-05",
    lastActive: "Deactivated on Jun 1, 2026",
    activitySummary: "Account deactivated by Admin",
  },
];
