import type { BorrowRequest } from "@/types/borrow-requests";

export const MOCK_DEPARTMENTS = [
  "All Departments",
  "IT",
  "Finance",
  "HR",
  "Engineering",
  "Admin",
  "Communications",
  "Executive",
  "Operations",
];

export const INITIAL_MOCK_REQUESTS: BorrowRequest[] = [
  {
    id: "br-001",
    requestCode: "REQ-2026-0081",
    requesterName: "Maria Santos",
    requesterEmail: "m.santos@crmc.gov.ph",
    requesterPhone: "+63 917 555 0192",
    department: "IT",
    itemDescription: "Dell Latitude 5420 Laptop (2 units)",
    assetCode: "CP-080, CP-081",
    category: "computing",
    quantity: 2,
    purpose: "Off-site technical training seminar for regional IT staff.",
    requestedAt: "2026-07-26T08:30:00Z",

    expectedReturnDate: "2026-08-02",
    status: "pending",
    notes: "Requires pre-installed VPN and development software tools.",
    history: [
      {
        id: "h-1",
        action: "submitted",
        actor: "Maria Santos",
        timestamp: "2026-07-26 08:30 AM",
        note: "Request submitted via Public Portal",
      },
    ],
  },
  {
    id: "br-002",
    requestCode: "REQ-2026-0082",
    requesterName: "Juan dela Cruz",
    requesterEmail: "j.delacruz@crmc.gov.ph",
    requesterPhone: "+63 918 555 0143",
    department: "Finance",
    itemDescription: "Epson PowerLite LCD Projector #A-102",
    assetCode: "AV-014",
    category: "av",
    quantity: 1,
    purpose: "Quarterly financial review presentation with department heads.",
    requestedAt: "2026-07-26T14:00:00Z",

    expectedReturnDate: "2026-07-30",
    status: "pending",
    notes: "Includes HDMI cable and wireless clicker remote.",
    history: [
      {
        id: "h-2",
        action: "submitted",
        actor: "Juan dela Cruz",
        timestamp: "2026-07-26 02:00 PM",
        note: "Request submitted via Public Portal",
      },
    ],
  },
  {
    id: "br-003",
    requestCode: "REQ-2026-0083",
    requesterName: "Rosa Reyes",
    requesterEmail: "r.reyes@crmc.gov.ph",
    requesterPhone: "+63 919 555 0884",
    department: "HR",
    itemDescription: "Ergonomic Mesh Office Chair",
    assetCode: "FN-045",
    category: "furniture",
    quantity: 1,
    purpose: "Temporary ergonomic setup for onboarding specialist.",
    requestedAt: "2026-07-27T09:15:00Z",

    expectedReturnDate: "2026-08-10",
    status: "pending",
    history: [
      {
        id: "h-3",
        action: "submitted",
        actor: "Rosa Reyes",
        timestamp: "2026-07-27 09:15 AM",
        note: "Request submitted via Public Portal",
      },
    ],
  },
  {
    id: "br-004",
    requestCode: "REQ-2026-0084",
    requesterName: "Carlos Mendoza",
    requesterEmail: "c.mendoza@crmc.gov.ph",
    requesterPhone: "+63 920 555 0731",
    department: "Engineering",
    itemDescription: "High-Speed HDMI Extension Cable (3 units)",
    assetCode: "AV-090",
    category: "av",
    quantity: 3,
    purpose: "Facility AV routing setup in Conference Room B.",
    requestedAt: "2026-07-27T11:00:00Z",

    expectedReturnDate: "2026-07-31",
    status: "pending",
    history: [
      {
        id: "h-4",
        action: "submitted",
        actor: "Carlos Mendoza",
        timestamp: "2026-07-27 11:00 AM",
        note: "Request submitted via Public Portal",
      },
    ],
  },
  {
    id: "br-005",
    requestCode: "REQ-2026-0085",
    requesterName: "Ana Villanueva",
    requesterEmail: "a.villanueva@crmc.gov.ph",
    requesterPhone: "+63 921 555 0228",
    department: "Admin",
    itemDescription: "Toyota Coaster Utility Van (Service Vehicle)",
    assetCode: "TR-004",
    category: "transport",
    quantity: 1,
    purpose: "Transporting medical conference supplies to satellite clinic.",
    requestedAt: "2026-07-28T07:45:00Z",

    expectedReturnDate: "2026-07-29",
    status: "pending",
    history: [
      {
        id: "h-5",
        action: "submitted",
        actor: "Ana Villanueva",
        timestamp: "2026-07-28 07:45 AM",
        note: "Request submitted via Public Portal",
      },
    ],
  },
  {
    id: "br-006",
    requestCode: "REQ-2026-0078",
    requesterName: "Ben Aquino",
    requesterEmail: "b.aquino@crmc.gov.ph",
    requesterPhone: "+63 922 555 0991",
    department: "Communications",
    itemDescription: "Canon EOS 90D DSLR Camera Kit",
    assetCode: "AV-031",
    category: "av",
    quantity: 1,
    purpose: "Coverage of hospital anniversary ceremony and press launch.",
    requestedAt: "2026-07-20T10:00:00Z",

    expectedReturnDate: "2026-07-24",
    status: "approved",
    history: [
      {
        id: "h-6a",
        action: "submitted",
        actor: "Ben Aquino",
        timestamp: "2026-07-20 10:00 AM",
      },
      {
        id: "h-6b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-07-20 11:30 AM",
        note: "Approved for press release coverage.",
      },
    ],
  },
  {
    id: "br-007",
    requestCode: "REQ-2026-0075",
    requesterName: "Luz Castillo",
    requesterEmail: "l.castillo@crmc.gov.ph",
    requesterPhone: "+63 923 555 0412",
    department: "Finance",
    itemDescription: "MacBook Pro 16\" Workstation",
    assetCode: "CP-012",
    category: "computing",
    quantity: 1,
    purpose: "Budget modeling and audit report compilation.",
    requestedAt: "2026-07-18T13:20:00Z",

    expectedReturnDate: "2026-07-25",
    status: "approved",
    history: [
      {
        id: "h-7a",
        action: "submitted",
        actor: "Luz Castillo",
        timestamp: "2026-07-18 01:20 PM",
      },
      {
        id: "h-7b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-07-18 02:00 PM",
        note: "Approved for audit period.",
      },
    ],
  },
  {
    id: "br-008",
    requestCode: "REQ-2026-0072",
    requesterName: "Dr. Gabriel Soriano",
    requesterEmail: "g.soriano@crmc.gov.ph",
    requesterPhone: "+63 924 555 0663",
    department: "Executive",
    itemDescription: "Executive Folding Conference Table",
    assetCode: "FN-012",
    category: "furniture",
    quantity: 2,
    purpose: "Board meeting overflow seating.",
    requestedAt: "2026-07-15T09:00:00Z",

    expectedReturnDate: "2026-07-16",
    status: "rejected",
    rejectionReason: "Item reserved for Board of Directors annual general assembly on requested dates.",
    history: [
      {
        id: "h-8a",
        action: "submitted",
        actor: "Dr. Gabriel Soriano",
        timestamp: "2026-07-15 09:00 AM",
      },
      {
        id: "h-8b",
        action: "rejected",
        actor: "Property Custodian",
        timestamp: "2026-07-15 10:15 AM",
        note: "Item reserved for Board of Directors annual general assembly on requested dates.",
      },
    ],
  },
  {
    id: "br-009",
    requestCode: "REQ-2026-0065",
    requesterName: "Mark Anthony Tan",
    requesterEmail: "m.tan@crmc.gov.ph",
    requesterPhone: "+63 925 555 0834",
    department: "Operations",
    itemDescription: "Portable Wireless PA System Kit",
    assetCode: "AV-008",
    category: "av",
    quantity: 1,
    purpose: "Community health outreach program announcement in Barangay Central.",
    requestedAt: "2026-07-10T08:00:00Z",

    expectedReturnDate: "2026-07-12",
    status: "returned",
    history: [
      {
        id: "h-9a",
        action: "submitted",
        actor: "Mark Anthony Tan",
        timestamp: "2026-07-10 08:00 AM",
      },
      {
        id: "h-9b",
        action: "approved",
        actor: "Property Custodian",
        timestamp: "2026-07-10 08:45 AM",
      },
      {
        id: "h-9c",
        action: "returned",
        actor: "Property Custodian",
        timestamp: "2026-07-12 04:30 PM",
        note: "Returned in good working condition.",
      },
    ],
  },
];
