"use client";

import React, { useState, useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  X,
  FilePlus2,
  Wallet,
  Building2,
  Boxes,
  Calendar,
  CreditCard,
  FileText,
  Search,
  Check,
  Loader2,
  CheckCircle2,
  Layers,
  ArrowRight,
  RotateCcw,
  Banknote,
  Lock,
  ListOrdered,
  Plus,
  Trash2,
  Sparkles,
  RefreshCw,
} from "lucide-react";
import { useToast } from "@/components/providers/toast-context";
import {
  useCreatePettyCashMutation,
  useNextPcvCodeQuery,
} from "@/features/petty-cash/client";
import { usePurchaseLotsQuery } from "@/features/purchase-lots/client/use-purchase-lots";
import { useSuppliersQuery } from "@/features/suppliers/client/use-suppliers";
import { useDepartmentsQuery } from "@/features/departments/client/use-departments";
import { useUsersQuery } from "@/features/users/client";
import { groupLotsByPO, type GroupedPurchaseOrder } from "@/types/grouped-purchase-order";
import { formatPhp } from "@/components/projects/format-money";
import { PETTY_CASH_CATEGORIES } from "@/types/petty-cash";
import { cn } from "@/lib/utils";
import { filterMoneyInput } from "@/lib/numeric-input";
import { SearchableSelect } from "@/components/ui/searchable-select";
import { MultiSelectDropdown } from "@/components/ui/multi-select-dropdown";
import {
  serializeParticulars,
  sumParticularAmounts,
  resolveDepartmentsFromPo,
  particularsFromPurchaseOrderLines,
  type ParticularLineItem,
} from "@/lib/voucher-particulars";

interface CreatePettyCashDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: () => void;
}

export function CreatePettyCashDialog({
  isOpen,
  onClose,
  onSuccess,
}: CreatePettyCashDialogProps) {
  const toast = useToast();
  const currentYear = new Date().getFullYear();
  const prefix = `PCV${currentYear}-`;

  // Form states
  const [codeSuffix, setCodeSuffix] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(true);
  const [voucherDate, setVoucherDate] = useState(
    () => new Date().toISOString().slice(0, 10)
  );
  const [payeeName, setPayeeName] = useState("");
  const [amount, setAmount] = useState("");
  const [category, setCategory] = useState("supplies");
  const [supplierId, setSupplierId] = useState<string | null>(null);
  const [supplierName, setSupplierName] = useState("");
  const [purchaseOrderNumber, setPurchaseOrderNumber] = useState("");
  const [departmentId, setDepartmentId] = useState<string | null>(null);
  const [departmentIds, setDepartmentIds] = useState<string[]>([]);
  const [receiptNumber, setReceiptNumber] = useState("");
  const [purpose, setPurpose] = useState("");
  const [listItems, setListItems] = useState<ParticularLineItem[]>([
    { description: "", amount: "" },
  ]);
  const [isLegacy, setIsLegacy] = useState(false);

  // PO Search state for the second column
  const [poSearch, setPoSearch] = useState("");

  // Queries
  const { data: lots = [] } = usePurchaseLotsQuery({ enabled: isOpen });
  const { data: suppliers = [] } = useSuppliersQuery({ enabled: isOpen, activeOnly: true });
  const { data: departments = [] } = useDepartmentsQuery({ enabled: isOpen });

  const categoryOptions = useMemo(
    () =>
      PETTY_CASH_CATEGORIES.map((cat) => ({
        value: cat.id,
        label: cat.label,
      })),
    []
  );

  const departmentOptions = useMemo(
    () =>
      departments.map((d) => ({
        value: d.id,
        label: `${d.name} (${d.code})`,
        keywords: d.code,
      })),
    [departments]
  );
  const { data: users = [] } = useUsersQuery({ enabled: isOpen });
  const {
    data: nextCodeData,
    isLoading: isLoadingNextCode,
    refetch: refetchNextCode,
  } = useNextPcvCodeQuery(isOpen);

  const groupedPOs = useMemo(() => {
    // Only POs that are not yet linked to an active voucher or petty cash.
    return groupLotsByPO(lots).filter((po) => !po.representative.disbursement);
  }, [lots]);

  // Filtered PO list based on user search in the second column
  const filteredPOs = useMemo(() => {
    if (!poSearch.trim()) return groupedPOs;
    const q = poSearch.toLowerCase().trim();
    return groupedPOs.filter((po) => {
      const poNum = (po.poNumber || "").toLowerCase();
      const supp = (po.representative.supplierName || "").toLowerCase();
      const item = (po.representative.itemName || "").toLowerCase();
      return poNum.includes(q) || supp.includes(q) || item.includes(q);
    });
  }, [groupedPOs, poSearch]);

  const createMutation = useCreatePettyCashMutation();

  // Reset state on open
  useEffect(() => {
    if (isOpen) {
      setIsAutoGenerated(true);
      setCodeSuffix("");
      setVoucherDate(new Date().toISOString().slice(0, 10));
      setPayeeName("");
      setAmount("");
      setCategory("supplies");
      setSupplierId(null);
      setSupplierName("");
      setPurchaseOrderNumber("");
      setDepartmentId(null);
      setDepartmentIds([]);
      setReceiptNumber("");
      setPurpose("");
      setListItems([{ description: "", amount: "" }]);
      setIsLegacy(false);
      setPoSearch("");
    }
  }, [isOpen]);

  // Sync auto-generated code suffix once loaded or refetched
  useEffect(() => {
    if (isOpen && nextCodeData?.pcvNumber && isAutoGenerated) {
      const generatedSuffix = nextCodeData.pcvNumber.startsWith(prefix)
        ? nextCodeData.pcvNumber.slice(prefix.length)
        : nextCodeData.pcvNumber;
      setCodeSuffix(generatedSuffix);
    }
  }, [isOpen, nextCodeData, prefix, isAutoGenerated]);

  const handleRegenerateCode = async () => {
    setIsAutoGenerated(true);
    try {
      const res = await refetchNextCode();
      if (res.data?.pcvNumber) {
        const generatedSuffix = res.data.pcvNumber.startsWith(prefix)
          ? res.data.pcvNumber.slice(prefix.length)
          : res.data.pcvNumber;
        setCodeSuffix(generatedSuffix);
        toast.success(`Generated petty cash voucher number ${res.data.pcvNumber}`);
      }
    } catch {
      toast.error("Failed to generate voucher number.");
    }
  };

  // Handle PO selection and auto-fill purpose + line items + department
  const applyPoSelection = (po: GroupedPurchaseOrder) => {
    setPurchaseOrderNumber(po.poNumber);
    const suppName = po.representative.supplierName || "";
    setSupplierName(suppName);
    setPayeeName(suppName);
    setSupplierId(po.representative.supplierId || null);

    const rawItems =
      po.lineItems && po.lineItems.length > 0
        ? po.lineItems
        : po.representative
          ? [po.representative]
          : [];

    const formattedList = particularsFromPurchaseOrderLines(rawItems);
    const fallbackAmount = po.totalCost ? Number(po.totalCost).toFixed(2) : "0.00";
    const lineTotal = sumParticularAmounts(formattedList);
    setListItems(
      formattedList.some((i) => i.description)
        ? formattedList
        : [
            {
              description: `Items from Purchase Order #${po.poNumber}`,
              amount: fallbackAmount,
            },
          ]
    );
    setAmount(lineTotal > 0 ? lineTotal.toFixed(2) : fallbackAmount);
    setPurpose(`Petty cash disbursement for Purchase Order #${po.poNumber}`);

    const resolvedDepts = resolveDepartmentsFromPo(
      [po.representative, ...po.lineItems],
      departments,
      users
    );
    setDepartmentIds(resolvedDepts.map((d) => d.id));
    setDepartmentId(resolvedDepts[0]?.id ?? null);
  };

  const handleSelectPO = (po: GroupedPurchaseOrder) => {
    if (isLegacy) return;
    applyPoSelection(po);
  };

  useEffect(() => {
    if (!isOpen || !purchaseOrderNumber || isLegacy) return;
    if (departments.length === 0) return;
    const po = groupedPOs.find((p) => p.poNumber === purchaseOrderNumber);
    if (!po) return;
    const resolvedDepts = resolveDepartmentsFromPo(
      [po.representative, ...po.lineItems],
      departments,
      users
    );
    const nextIds = resolvedDepts.map((d) => d.id);
    const same =
      nextIds.length === departmentIds.length &&
      nextIds.every((id, i) => id === departmentIds[i]);
    if (!same) {
      setDepartmentIds(nextIds);
      setDepartmentId(nextIds[0] ?? null);
    }
  }, [
    isOpen,
    purchaseOrderNumber,
    isLegacy,
    departments,
    users,
    groupedPOs,
    departmentIds,
  ]);

  const handleClearPO = () => {
    setPurchaseOrderNumber("");
    setPayeeName("");
    setAmount("");
    setPurpose("");
    setListItems([{ description: "", amount: "" }]);
    setSupplierId(null);
    setSupplierName("");
    setDepartmentId(null);
    setDepartmentIds([]);
  };

  const isPoLinked = Boolean(purchaseOrderNumber) && !isLegacy;

  const syncAmountFromLines = (items: ParticularLineItem[]) => {
    if (isPoLinked) return;
    const total = sumParticularAmounts(items);
    if (total > 0) {
      setAmount(total.toFixed(2));
    }
  };

  const handleItemChange = (
    index: number,
    field: keyof ParticularLineItem,
    val: string
  ) => {
    if (isPoLinked) return;
    setListItems((prev) => {
      const updated = [...prev];
      const nextVal =
        field === "amount" ? (filterMoneyInput(val) ?? prev[index].amount) : val;
      updated[index] = { ...updated[index], [field]: nextVal };
      if (field === "amount") {
        syncAmountFromLines(updated);
      }
      return updated;
    });
  };

  const handleAddItem = () => {
    if (isPoLinked) return;
    setListItems((prev) => [...prev, { description: "", amount: "" }]);
  };

  const handleRemoveItem = (index: number) => {
    if (isPoLinked) return;
    setListItems((prev) => {
      if (prev.length <= 1) return [{ description: "", amount: "" }];
      const next = prev.filter((_, i) => i !== index);
      syncAmountFromLines(next);
      return next;
    });
  };

  const handleItemKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (isPoLinked) return;
    if (e.key === "Enter") {
      e.preventDefault();
      handleAddItem();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const trimmedSuffix = codeSuffix.trim();
    const effectivePcvNumber = trimmedSuffix
      ? `${prefix}${trimmedSuffix}`
      : nextCodeData?.pcvNumber || undefined;

    if (!effectivePcvNumber && !trimmedSuffix) {
      toast.error("Voucher Number is required. Click Regenerate to assign one automatically.");
      return;
    }

    if (!payeeName.trim()) {
      toast.error("Payee / Recipient is required. Please enter who the funds are disbursed to.");
      return;
    }

    if (!amount || parseFloat(amount) < 0) {
      toast.error("Amount is required and must be 0.00 or greater.");
      return;
    }

    const finalParticulars = serializeParticulars(listItems);

    const selectedDepts = departmentIds
      .map((id) => departments.find((d) => d.id === id))
      .filter((d): d is NonNullable<typeof d> => Boolean(d));
    const selectedDept = selectedDepts[0];

    try {
      const created = await createMutation.mutateAsync({
        pcvNumber: effectivePcvNumber,
        status: "draft",
        voucherDate,
        payeeName: payeeName.trim(),
        amount: amount || "0",
        category,
        supplierId: supplierId || null,
        supplierName: supplierName.trim() || null,
        purchaseOrderNumber: purchaseOrderNumber.trim() || null,
        departmentId: selectedDept?.id || departmentId || null,
        departmentName:
          selectedDepts.map((d) => d.name).join(", ") ||
          selectedDept?.name ||
          null,
        departmentIds: selectedDepts.map((d) => d.id),
        receiptNumber: receiptNumber.trim() || null,
        purpose: purpose.trim(),
        particulars: finalParticulars,
        isLegacy,
      });

      const displayCode = created?.pcvNumber || effectivePcvNumber || "Petty Cash Voucher";
      toast.success(`Petty Cash Voucher ${displayCode} saved as draft.`);

      onSuccess?.();
      onClose();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "An unexpected error occurred. Please try again.";
      toast.error(msg);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.96, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.96, y: 10 }}
            transition={{
              type: "spring",
              damping: 26,
              stiffness: 300,
            }}
            className="relative w-full max-w-5xl max-h-[90vh] flex flex-col rounded-2xl border border-border bg-bg shadow-2xl overflow-hidden"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-bg-subtle/50 shrink-0">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                  <Wallet className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-base font-bold text-text">Create Petty Cash Voucher</h2>
                  <p className="text-xs text-text-secondary">
                    Record micro-disbursements for immediate small expenses and emergency purchases
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={onClose}
                className="rounded-lg p-1.5 text-text-secondary hover:bg-bg hover:text-text transition-colors"
                aria-label="Close dialog"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Content Container (Permanent 2-column layout: Form + PO Search) */}
            <div className="flex-1 min-h-0 overflow-y-auto">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 p-6">
                {/* Left Column: Form */}
                <form
                  id="petty-cash-form"
                  onSubmit={handleSubmit}
                  className="space-y-4.5 lg:col-span-7"
                >
                  {/* PCV Code: Automated generation with manual override capability */}
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <div className="flex items-center gap-2">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Voucher Number
                          <span className="text-rose-500 font-bold ml-1">*</span>
                        </label>
                        {isAutoGenerated && (
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-full">
                            <Sparkles className="h-3 w-3" />
                            Auto-generated
                          </span>
                        )}
                      </div>
                      <button
                        type="button"
                        onClick={handleRegenerateCode}
                        disabled={isLoadingNextCode}
                        className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors cursor-pointer disabled:opacity-50"
                        title="Generate next sequential voucher number"
                      >
                        <RefreshCw className={cn("h-3.5 w-3.5", isLoadingNextCode && "animate-spin")} />
                        <span>{isLoadingNextCode ? "Generating..." : "Regenerate"}</span>
                      </button>
                    </div>
                    <div className="flex rounded-lg border border-border overflow-hidden focus-within:ring-2 focus-within:ring-primary/20 focus-within:border-primary">
                      <div className="flex items-center bg-bg-subtle px-3.5 py-2 border-r border-border text-sm font-semibold text-text select-none font-mono">
                        {prefix}
                      </div>
                      <input
                        type="text"
                        value={codeSuffix}
                        onChange={(e) => {
                          setIsAutoGenerated(false);
                          setCodeSuffix(e.target.value.replace(/\s+/g, ""));
                        }}
                        placeholder={isLoadingNextCode ? "Generating..." : "000001"}
                        maxLength={20}
                        required
                        className="flex-1 bg-transparent px-3.5 py-2 text-sm text-text placeholder:text-text-secondary/50 focus:outline-hidden font-mono font-medium"
                      />
                    </div>
                    <p className="mt-1 text-[11px] text-text-secondary flex items-center justify-between">
                      <span>
                        Prefix <code className="font-semibold text-emerald-600 dark:text-emerald-400">{prefix}</code> is automated from fiscal year.
                      </span>
                      <span className="text-text-secondary/70">
                        Edit suffix to manually override
                      </span>
                    </p>
                  </div>

                  {/* Expense Category & Date */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Category
                          <span className="text-rose-500 font-bold ml-1">*</span>
                        </label>
                        <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-1.5 py-0.5 rounded">
                          Petty Cash
                        </span>
                      </div>
                      <SearchableSelect
                        value={category}
                        onValueChange={setCategory}
                        options={categoryOptions}
                        placeholder="Type to find a category…"
                        aria-required="true"
                        inputClassName="text-sm py-2"
                      />
                      <p className="mt-1 text-[11px] text-text-secondary">
                        Classification of micro-disbursement expense.
                      </p>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Voucher Date
                          <span className="text-rose-500 font-bold ml-1">*</span>
                        </label>
                        <span className="text-[11px] font-semibold text-rose-500 bg-rose-500/10 px-1.5 py-0.5 rounded">
                          Required
                        </span>
                      </div>
                      <input
                        type="date"
                        value={voucherDate}
                        onChange={(e) => setVoucherDate(e.target.value)}
                        required
                        className="w-full rounded-lg border border-border bg-bg px-3.5 py-2 text-sm text-text focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary"
                      />
                    </div>
                  </div>

                  {/* Legacy / Unlinked Toggle */}
                  <div className="flex items-center justify-between rounded-lg border border-border bg-bg-subtle/40 p-3.5">
                    <div className="flex items-center gap-3">
                      <input
                        id="legacy-toggle"
                        type="checkbox"
                        checked={isLegacy}
                        onChange={(e) => {
                          const checked = e.target.checked;
                          setIsLegacy(checked);
                          if (checked) {
                            handleClearPO();
                          }
                        }}
                        className="h-4 w-4 rounded border-border text-primary focus:ring-primary/20 cursor-pointer"
                      />
                      <label htmlFor="legacy-toggle" className="text-xs font-semibold text-text cursor-pointer select-none">
                        Historical / Legacy Petty Cash Entry
                        <span className="block text-[11px] font-normal text-text-secondary">
                          Use for backlog or historical micro-disbursements without an existing system PO.
                        </span>
                      </label>
                    </div>
                  </div>

                  {/* Linked PO Badge (If selected) */}
                  {purchaseOrderNumber && (
                    <motion.div
                      initial={{ opacity: 0, y: -4 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="flex items-center justify-between rounded-lg border border-primary/25 bg-primary/10 px-3.5 py-2.5 text-xs"
                    >
                      <div className="flex items-center gap-2 text-primary font-semibold">
                        <Boxes className="h-4 w-4" />
                        <span>Linked to PO #{purchaseOrderNumber}</span>
                        <span className="text-[10px] font-normal text-text-secondary bg-bg px-1.5 py-0.5 rounded border border-border/60">
                          Line items auto-filled
                        </span>
                      </div>
                      <button
                        type="button"
                        onClick={handleClearPO}
                        className="text-[11px] font-semibold text-rose-600 hover:underline cursor-pointer"
                      >
                        Clear Link
                      </button>
                    </motion.div>
                  )}

                  {/* Payee Name & Amount */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Payee / Recipient
                          <span className="text-rose-500 font-bold ml-1">*</span>
                        </label>
                        <span className="text-[11px] font-semibold text-rose-500 bg-rose-500/10 px-1.5 py-0.5 rounded">
                          Required
                        </span>
                      </div>
                      <input
                        type="text"
                        value={payeeName}
                        onChange={(e) => setPayeeName(e.target.value)}
                        placeholder="e.g. Employee Name, Purchaser, or Payee"
                        required
                        className="w-full rounded-lg border border-border bg-bg px-3.5 py-2 text-sm text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary"
                      />
                      <p className="mt-1 text-[11px] text-text-secondary">
                        Person receiving or claiming the petty cash fund.
                      </p>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Amount (PHP)
                          <span className="text-rose-500 font-bold ml-1">*</span>
                        </label>
                        {isPoLinked ? (
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-700 dark:text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded-full">
                            <Lock className="h-3 w-3" />
                            From linked PO
                          </span>
                        ) : (
                          <span className="text-[11px] font-semibold text-rose-500 bg-rose-500/10 px-1.5 py-0.5 rounded">
                            Required
                          </span>
                        )}
                      </div>
                      <input
                        type="number"
                        step="0.01"
                        min="0"
                        value={amount}
                        onChange={(e) => {
                          if (!isPoLinked) setAmount(e.target.value);
                        }}
                        placeholder="0.00"
                        required
                        readOnly={isPoLinked}
                        disabled={isPoLinked}
                        className={cn(
                          "w-full rounded-lg border border-border bg-bg px-3.5 py-2 text-sm font-mono text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary",
                          isPoLinked && "cursor-not-allowed opacity-75 bg-bg-subtle"
                        )}
                      />
                      <p className="mt-1 text-[11px] text-text-secondary">
                        {isPoLinked
                          ? "Amount is calculated from the linked PO line items and cannot be edited."
                          : "Total cash disbursed for this expense."}
                      </p>
                    </div>
                  </div>

                  {/* Supplier & Receipt / Slip No */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Supplier / Store
                        </label>
                        <span className="text-[11px] text-text-secondary">
                          Optional
                        </span>
                      </div>
                      <input
                        type="text"
                        value={supplierName}
                        onChange={(e) => setSupplierName(e.target.value)}
                        placeholder="Merchant, store, or vendor"
                        className="w-full rounded-lg border border-border bg-bg px-3.5 py-2 text-sm text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary"
                      />
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Receipt / Slip No.
                        </label>
                        <span className="text-[11px] text-text-secondary">
                          Optional
                        </span>
                      </div>
                      <input
                        type="text"
                        value={receiptNumber}
                        onChange={(e) => setReceiptNumber(e.target.value)}
                        placeholder="e.g. OR #, Sales Invoice #, Trip Ticket #"
                        className="w-full rounded-lg border border-border bg-bg px-3.5 py-2 text-sm font-mono text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary"
                      />
                    </div>
                  </div>

                  {/* Department (locked when PO linked) */}
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="text-xs font-semibold uppercase tracking-wider text-text">
                        Requesting Department
                      </label>
                      {isPoLinked ? (
                        <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-700 dark:text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded-full">
                          <Lock className="h-3 w-3" />
                          From linked PO
                        </span>
                      ) : (
                        <span className="text-[11px] text-text-secondary">
                          Optional
                        </span>
                      )}
                    </div>
                    <MultiSelectDropdown
                      label="Departments"
                      icon={Building2}
                      variant="form"
                      searchable
                      selectedIds={departmentIds}
                      onToggle={(id) => {
                        if (isPoLinked) return;
                        setDepartmentIds((prev) => {
                          const next = prev.includes(id)
                            ? prev.filter((x) => x !== id)
                            : [...prev, id];
                          setDepartmentId(next[0] || null);
                          return next;
                        });
                      }}
                      options={departmentOptions.map((o) => ({
                        id: o.value,
                        label: o.label,
                      }))}
                      disabled={isPoLinked}
                      placeholder={
                        isPoLinked
                          ? departmentIds.length > 0
                            ? "From linked PO"
                            : "No department on linked PO"
                          : "Type to find one or more departments…"
                      }
                      emptyMessage="No departments available"
                      triggerClassName={cn(
                        "text-sm py-2",
                        isPoLinked && "opacity-75 bg-bg-subtle"
                      )}
                    />
                    {isPoLinked ? (
                      <p className="mt-1 text-[11px] text-text-secondary">
                        {departmentIds.length > 1
                          ? "All sponsoring departments from the linked purchase order."
                          : "Department is taken from the linked purchase order and cannot be changed until the PO link is cleared."}
                      </p>
                    ) : (
                      <p className="mt-1 text-[11px] text-text-secondary">
                        First selected department is primary.
                      </p>
                    )}
                  </div>

                  {/* Purpose (paragraph) + Particulars (itemized with costs) */}
                  <div className="space-y-3">
                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <label className="text-xs font-semibold uppercase tracking-wider text-text">
                          Purpose
                        </label>
                        <span className="text-[11px] text-text-secondary">
                          Optional
                        </span>
                      </div>
                      <textarea
                        rows={3}
                        value={purpose}
                        onChange={(e) => setPurpose(e.target.value)}
                        placeholder="Briefly state why petty cash is needed (e.g. urgent supplies, fare reimbursement, emergency repair)..."
                        className="w-full rounded-lg border border-border bg-bg p-3 text-sm text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary resize-none"
                      />
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <div className="flex items-center gap-2">
                          <label className="text-xs font-semibold uppercase tracking-wider text-text">
                            Particulars
                          </label>
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-text-secondary">
                            <ListOrdered className="h-3 w-3" />
                            {isPoLinked ? "PO line items" : "Itemized list"}
                          </span>
                        </div>
                        {isPoLinked ? (
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-700 dark:text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded-full">
                            <Lock className="h-3 w-3" />
                            From linked PO
                          </span>
                        ) : (
                          <span className="text-[11px] text-text-secondary">
                            Optional
                          </span>
                        )}
                      </div>

                      <div className="rounded-lg border border-border bg-bg-subtle/30 p-2.5 space-y-2">
                        <div className="grid grid-cols-[auto_minmax(0,1fr)_6.5rem_auto] gap-2 px-0.5 text-[10px] font-semibold uppercase tracking-wider text-text-secondary">
                          <span className="w-7 text-center">#</span>
                          <span>Description</span>
                          <span className="text-right pr-1">Cost</span>
                          <span className="w-8" />
                        </div>

                        <div className="space-y-1.5 max-h-48 overflow-y-auto pr-1">
                          {listItems.map((item, idx) => (
                            <div
                              key={idx}
                              className="grid grid-cols-[auto_minmax(0,1fr)_6.5rem_auto] gap-2 items-center"
                            >
                              <span className="flex items-center justify-center h-7 w-7 rounded-lg bg-bg border border-border text-xs font-mono font-semibold text-text-secondary shrink-0">
                                {idx + 1}
                              </span>
                              <input
                                type="text"
                                value={item.description}
                                onChange={(e) =>
                                  handleItemChange(idx, "description", e.target.value)
                                }
                                onKeyDown={handleItemKeyDown}
                                placeholder={`Item / expense #${idx + 1}...`}
                                readOnly={isPoLinked}
                                disabled={isPoLinked}
                                className={cn(
                                  "w-full rounded-lg border border-border bg-bg px-3 py-1.5 text-xs text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary",
                                  isPoLinked && "cursor-not-allowed bg-bg-subtle"
                                )}
                              />
                              <input
                                type="text"
                                inputMode="decimal"
                                value={item.amount}
                                onChange={(e) =>
                                  handleItemChange(idx, "amount", e.target.value)
                                }
                                placeholder="0.00"
                                readOnly={isPoLinked}
                                disabled={isPoLinked}
                                className={cn(
                                  "w-full rounded-lg border border-border bg-bg px-2 py-1.5 text-xs font-mono text-right text-text placeholder:text-text-secondary/50 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary",
                                  isPoLinked && "cursor-not-allowed bg-bg-subtle"
                                )}
                              />
                              <button
                                type="button"
                                onClick={() => handleRemoveItem(idx)}
                                disabled={
                                  isPoLinked ||
                                  (listItems.length <= 1 &&
                                    idx === 0 &&
                                    !item.description &&
                                    !item.amount)
                                }
                                className="p-1.5 text-text-secondary hover:text-red-500 rounded-lg hover:bg-bg transition-colors cursor-pointer disabled:opacity-30 disabled:hover:text-text-secondary disabled:cursor-not-allowed"
                                title={isPoLinked ? "Locked to PO line items" : "Remove item"}
                              >
                                <Trash2 className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          ))}
                        </div>

                        <div className="flex items-center justify-between pt-1 border-t border-border/50">
                          <span className="text-[11px] text-text-secondary">
                            {isPoLinked
                              ? "Particulars are linked to the selected PO line items."
                              : (
                                <>
                                  Line costs update the total amount when provided. Press{" "}
                                  <kbd className="px-1 py-0.5 text-[10px] font-mono bg-bg rounded border border-border">
                                    Enter
                                  </kbd>{" "}
                                  to add a row.
                                </>
                              )}
                          </span>
                          {!isPoLinked ? (
                            <button
                              type="button"
                              onClick={handleAddItem}
                              className="flex items-center gap-1 px-2.5 py-1 text-xs font-medium text-text bg-bg hover:bg-bg-subtle border border-border rounded-lg transition-colors cursor-pointer shadow-2xs"
                            >
                              <Plus className="h-3 w-3" />
                              Add Item
                            </button>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>
                </form>

                {/* Right Column: PO Explorer (Disabled when legacy mode is selected) */}
                <div
                  className={cn(
                    "lg:col-span-5 flex flex-col rounded-lg border border-border bg-bg-subtle/40 p-4 space-y-3 transition-opacity",
                    isLegacy && "opacity-75"
                  )}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs font-bold text-text">
                      <Boxes className="h-4 w-4 text-primary" />
                      <span>Attach Existing Purchase Order</span>
                    </div>
                    {isLegacy ? (
                      <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-amber-600 dark:text-amber-400">
                        <Lock className="h-3 w-3" />
                        Disabled
                      </span>
                    ) : (
                      <span className="text-[11px] text-text-secondary font-medium">
                        {filteredPOs.length} available
                      </span>
                    )}
                  </div>

                  {/* Warning banner when in legacy mode */}
                  {isLegacy && (
                    <div className="flex items-center gap-2 rounded-lg bg-amber-500/10 border border-amber-500/20 px-3 py-2 text-xs text-amber-700 dark:text-amber-400">
                      <Lock className="h-3.5 w-3.5 shrink-0" />
                      <span>Historical mode active: Linking existing POs is disabled.</span>
                    </div>
                  )}

                  {/* PO Search Box */}
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-text-secondary" />
                    <input
                      type="text"
                      disabled={isLegacy}
                      value={poSearch}
                      onChange={(e) => setPoSearch(e.target.value)}
                      placeholder={isLegacy ? "PO search disabled in legacy mode" : "Search PO#, supplier, or item..."}
                      className={cn(
                        "w-full rounded-lg border border-border bg-bg pl-8 pr-7 py-1.5 text-xs text-text placeholder:text-text-secondary/60 focus:outline-hidden focus:ring-2 focus:ring-primary/20 focus:border-primary",
                        isLegacy && "cursor-not-allowed bg-bg-subtle opacity-70"
                      )}
                    />
                    {poSearch && !isLegacy && (
                      <button
                        type="button"
                        onClick={() => setPoSearch("")}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-text-secondary hover:text-text"
                      >
                        <X className="h-3.5 w-3.5" />
                      </button>
                    )}
                  </div>

                  {/* PO List */}
                  <div
                    className={cn(
                      "flex-1 min-h-107.5 max-h-125 overflow-y-auto divide-y divide-border/60 rounded-lg border border-border bg-bg",
                      isLegacy && "pointer-events-none select-none cursor-not-allowed opacity-60"
                    )}
                  >
                    {filteredPOs.length > 0 ? (
                      filteredPOs.map((po) => {
                        const isSelected = purchaseOrderNumber === po.poNumber;
                        return (
                          <div
                            key={po.poNumber}
                            onClick={() => {
                              if (!isLegacy) handleSelectPO(po);
                            }}
                            className={cn(
                              "p-3 text-xs transition-colors group",
                              isLegacy ? "cursor-not-allowed opacity-75" : "cursor-pointer hover:bg-bg-subtle/70",
                              isSelected && "bg-primary/10 border-l-4 border-l-primary"
                            )}
                          >
                            <div className="flex items-center justify-between gap-2">
                              <div
                                className={cn(
                                  "font-mono font-bold text-text transition-colors",
                                  !isLegacy && "group-hover:text-primary"
                                )}
                              >
                                #{po.poNumber}
                              </div>
                              <div className="font-mono font-bold text-emerald-600 dark:text-emerald-400">
                                {formatPhp(po.totalCost)}
                              </div>
                            </div>

                            <div className="mt-1 flex items-center justify-between gap-2 text-[11px] text-text-secondary">
                              <div className="flex items-center gap-1 max-w-50 truncate">
                                <Building2 className="h-3 w-3 shrink-0" />
                                <span className="truncate">{po.representative.supplierName || "No Supplier"}</span>
                              </div>
                              <span>{po.itemCount} item(s)</span>
                            </div>

                            <div className="mt-1 text-[11px] text-text-secondary truncate">
                              {po.representative.itemName}
                            </div>

                            <div className="mt-2 flex items-center justify-end">
                              {isSelected ? (
                                <span className="inline-flex items-center gap-1 text-[11px] font-bold text-primary">
                                  <Check className="h-3 w-3" />
                                  <span>Selected</span>
                                </span>
                              ) : !isLegacy ? (
                                <span className="text-[11px] font-semibold text-primary opacity-0 group-hover:opacity-100 transition-opacity">
                                  Click to Auto-fill &rarr;
                                </span>
                              ) : null}
                            </div>
                          </div>
                        );
                      })
                    ) : (
                      <div className="p-8 text-center text-xs text-text-secondary">
                        {poSearch.trim()
                          ? "No available purchase orders match your search."
                          : "No available purchase orders. POs already linked to a voucher or petty cash are hidden."}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Footer Actions */}
            <div className="px-6 py-4 border-t border-border bg-bg-subtle/50 flex items-center justify-between shrink-0">
              <div className="text-xs text-text-secondary">
                {isLegacy ? (
                  <span className="text-amber-600 dark:text-amber-400 font-medium flex items-center gap-1.5">
                    <Lock className="h-3.5 w-3.5" />
                    <span>Historical / Legacy mode: Purchase Order selection is disabled.</span>
                  </span>
                ) : (
                  <span>
                    Tip: Selecting a PO auto-fills the payee, amount, supplier, and purchase particulars.
                  </span>
                )}
              </div>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={onClose}
                  className="rounded-lg border border-border px-4 py-2 text-xs font-semibold text-text hover:bg-bg-subtle transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  form="petty-cash-form"
                  disabled={createMutation.isPending}
                  className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2 text-xs font-bold text-primary-foreground shadow-xs hover:bg-primary/90 transition-colors disabled:opacity-50"
                >
                  {createMutation.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Saving...</span>
                    </>
                  ) : (
                    <>
                      <FilePlus2 className="h-4 w-4" />
                      <span>Create Petty Cash</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
