import type { ConsumableItem } from "./types";

export const CONSUMABLE_CATEGORIES: { id: string; label: string }[] = [
  { id: "all", label: "All Categories" },
  { id: "paper", label: "Paper Products" },
  { id: "ink_toner", label: "Ink & Toner" },
  { id: "cleaning", label: "Cleaning & Sanitation" },
  { id: "office_supplies", label: "Office Supplies" },
  { id: "medical", label: "Medical Disposables" },
];

export const INITIAL_MOCK_CONSUMABLES: ConsumableItem[] = [
  {
    id: "con-001",
    itemCode: "CON-1001",
    name: "A4 Multipurpose Copy Paper 80gsm",
    category: "paper",
    unit: "reams",
    currentQty: 8,
    minThreshold: 25,
    location: "Supply Storage Bay A1",
    supplier: "PaperLine Philippines",
    lastRestocked: "2026-07-10",
    notes: "High consumption during quarterly financial reporting.",
    history: [
      { id: "sh-1", date: "2026-07-10", type: "restock", quantityChange: 50, actor: "Dave Custodio", notes: "PO #8841 Received" },
      { id: "sh-2", date: "2026-07-22", type: "adjustment", quantityChange: -42, actor: "Dave Custodio", reason: "Regular Dept Distribution", notes: "Issued to Finance & HR" },
    ],
  },
  {
    id: "con-002",
    itemCode: "CON-1002",
    name: "HP LaserJet Pro Black Toner Cartridge 26A",
    category: "ink_toner",
    unit: "cartridges",
    currentQty: 2,
    minThreshold: 5,
    location: "IT Storage Cabinet 2",
    supplier: "Silicon Valley Tech Sales",
    lastRestocked: "2026-06-15",
    notes: "Compatible with Admin & Medical Records printers.",
    history: [
      { id: "sh-3", date: "2026-06-15", type: "restock", quantityChange: 10, actor: "IT Supply", notes: "PO #8102" },
      { id: "sh-4", date: "2026-07-18", type: "adjustment", quantityChange: -8, actor: "IT Helpdesk", reason: "Normal Issue to Printers" },
    ],
  },
  {
    id: "con-003",
    itemCode: "CON-1003",
    name: "70% Isopropyl Alcohol (1 Gallon Container)",
    category: "cleaning",
    unit: "gallons",
    currentQty: 18,
    minThreshold: 15,
    location: "Housekeeping Depot B4",
    supplier: "HygienePro Corp",
    lastRestocked: "2026-07-20",
    notes: "Low stock boundary reached — near reorder threshold.",
    history: [
      { id: "sh-5", date: "2026-07-20", type: "restock", quantityChange: 30, actor: "Central Store", notes: "Bi-weekly delivery" },
      { id: "sh-6", date: "2026-07-26", type: "adjustment", quantityChange: -12, actor: "Housekeeping Supervisor", reason: "Distributed to Ward Refills" },
    ],
  },
  {
    id: "con-004",
    itemCode: "CON-1004",
    name: "Heavy Duty Nitrile Examination Gloves (Box of 100)",
    category: "medical",
    unit: "boxes",
    currentQty: 140,
    minThreshold: 50,
    location: "Central Medical Store R3",
    supplier: "MedTech Solutions",
    lastRestocked: "2026-07-25",
    notes: "Size Medium. High stock buffer maintained.",
    history: [
      { id: "sh-7", date: "2026-07-25", type: "restock", quantityChange: 200, actor: "Medical Supply Clerk", notes: "Monthly allotment" },
    ],
  },
  {
    id: "con-005",
    itemCode: "CON-1005",
    name: "Gel Ballpoint Pens 0.7mm Black (Box of 12)",
    category: "office_supplies",
    unit: "boxes",
    currentQty: 32,
    minThreshold: 10,
    location: "Supply Storage Bay A3",
    supplier: "National Book Store Bulk",
    lastRestocked: "2026-07-01",
    history: [],
  },
  {
    id: "con-006",
    itemCode: "CON-1006",
    name: "Disinfectant Surface Spray 500ml",
    category: "cleaning",
    unit: "bottles",
    currentQty: 0,
    minThreshold: 12,
    location: "Housekeeping Depot B4",
    supplier: "HygienePro Corp",
    lastRestocked: "2026-05-10",
    notes: "Out of stock — reorder requisition pending approval.",
    history: [
      { id: "sh-8", date: "2026-07-14", type: "adjustment", quantityChange: -4, actor: "Housekeeping", reason: "Used for Ward Sanitation", notes: "Stock depleted to zero" },
    ],
  },
  {
    id: "con-007",
    itemCode: "CON-1007",
    name: "Epson EcoTank Black Ink Refill Bottle T664",
    category: "ink_toner",
    unit: "bottles",
    currentQty: 14,
    minThreshold: 10,
    location: "IT Storage Cabinet 2",
    supplier: "Silicon Valley Tech Sales",
    lastRestocked: "2026-07-15",
    history: [],
  },
];
