import type { Asset } from "@/types/assets";

export const INITIAL_MOCK_ASSETS: Asset[] = [
  {
    id: "ast-001",
    assetCode: "CP-080",
    name: "Dell Latitude 5420 Laptop",
    category: "computing",
    status: "active",
    serialNumber: "SN-DL-98214-X",
    location: "IT Office — Room 302",
    currentHolder: "Maria Santos",
    department: "IT",
    purchaseDate: "2024-03-15",
    value: 58000,
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=60",
    notes: "Assigned for regional technical training setup.",
    lastUpdated: "2026-07-26",
    maintenanceHistory: [
      { id: "m-101", date: "2025-11-10", type: "inspection", description: "Annual hardware diagnostics & RAM check.", technician: "Dave Custodio" },
      { id: "m-102", date: "2026-03-02", type: "maintenance", description: "OS upgrade to Windows 11 Enterprise.", technician: "IT Helpdesk" },
    ],
  },
  {
    id: "ast-002",
    assetCode: "AV-031",
    name: "Canon EOS 90D DSLR Camera Kit",
    category: "av",
    status: "needs_repair",
    serialNumber: "SN-CN-44109-C",
    location: "Media Studio — Rm 104",
    currentHolder: "Ben Aquino",
    department: "Communications",
    purchaseDate: "2023-08-20",
    value: 72000,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60",
    notes: "Lens autofocus mechanism sticking intermittently.",
    lastUpdated: "2026-07-25",
    maintenanceHistory: [
      { id: "m-201", date: "2026-07-25", type: "flagged", description: "Autofocus gear ring sticky — scheduled for calibration.", technician: "Ben Aquino" },
    ],
  },
  {
    id: "ast-003",
    assetCode: "AV-014",
    name: "Epson PowerLite LCD Projector #A-102",
    category: "av",
    status: "active",
    serialNumber: "SN-EP-33821-P",
    location: "Main Auditorium AV Rack",
    currentHolder: undefined, // Available
    department: "AV Services",
    purchaseDate: "2024-01-10",
    value: 34000,
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&auto=format&fit=crop&q=60",
    notes: "Includes wireless remote & 10m HDMI bundle.",
    lastUpdated: "2026-07-24",
    maintenanceHistory: [
      { id: "m-301", date: "2025-09-15", type: "maintenance", description: "Air filter cleaning & lamp runtime reset.", technician: "AV Tech" },
    ],
  },
  {
    id: "ast-004",
    assetCode: "TR-004",
    name: "Toyota Coaster Utility Van (Patient/Staff Van)",
    category: "transport",
    status: "active",
    serialNumber: "VIN-TY-8849201",
    location: "Motorpool Bay 3",
    currentHolder: "Ana Villanueva",
    department: "Admin",
    purchaseDate: "2022-05-12",
    value: 2800000,
    notes: "Registration valid through Nov 2026.",
    lastUpdated: "2026-07-28",
    maintenanceHistory: [
      { id: "m-401", date: "2026-06-01", type: "maintenance", description: "50,000 km periodic engine oil change & tire rotation.", technician: "Central Garage" },
    ],
  },
  {
    id: "ast-005",
    assetCode: "FN-045",
    name: "Ergonomic Mesh High-Back Office Chair",
    category: "furniture",
    status: "active",
    serialNumber: "SN-HM-11029",
    location: "HR Executive Suite",
    currentHolder: "Rosa Reyes",
    department: "HR",
    purchaseDate: "2025-02-01",
    value: 14500,
    notes: "Adjustable lumbar support armrests.",
    lastUpdated: "2026-07-27",
    maintenanceHistory: [],
  },
  {
    id: "ast-006",
    assetCode: "CP-012",
    name: "MacBook Pro 16\" M3 Max Workstation",
    category: "computing",
    status: "active",
    serialNumber: "SN-AP-88392-M",
    location: "Finance Dept — Desk 12",
    currentHolder: "Luz Castillo",
    department: "Finance",
    purchaseDate: "2024-06-18",
    value: 165000,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60",
    notes: "High-spec graphics rig for audit modeling.",
    lastUpdated: "2026-07-18",
    maintenanceHistory: [],
  },
  {
    id: "ast-007",
    assetCode: "FN-012",
    name: "Modular Executive Conference Table",
    category: "furniture",
    status: "out_of_service",
    serialNumber: "SN-FN-99201",
    location: "Storage Annex B",
    currentHolder: undefined,
    department: "Executive",
    purchaseDate: "2021-11-05",
    value: 45000,
    notes: "Corner latch mechanism cracked during room relocation.",
    lastUpdated: "2026-07-15",
    maintenanceHistory: [
      { id: "m-701", date: "2026-07-15", type: "flagged", description: "Structural hinge pin bent — replacement hardware on order.", technician: "Carpentry Team" },
    ],
  },
  {
    id: "ast-008",
    assetCode: "AV-008",
    name: "Portable Wireless PA System Kit (Speakers + Mics)",
    category: "av",
    status: "active",
    serialNumber: "SN-PA-77291",
    location: "Community Outreach Locker",
    currentHolder: undefined,
    department: "Operations",
    purchaseDate: "2023-10-30",
    value: 26000,
    notes: "Includes 2 wireless handheld mics & charging dock.",
    lastUpdated: "2026-07-12",
    maintenanceHistory: [
      { id: "m-801", date: "2026-07-12", type: "inspection", description: "Rechargeable lithium battery capacity tested OK.", technician: "AV Tech" },
    ],
  },
  {
    id: "ast-009",
    assetCode: "TR-002",
    name: "Nissan Urvan Ambulance Unit #2",
    category: "transport",
    status: "retired",
    serialNumber: "VIN-NS-559201",
    location: "Decommissioned Depot",
    currentHolder: undefined,
    department: "Emergency",
    purchaseDate: "2015-04-10",
    value: 0,
    notes: "Decommissioned per Board Resolution #2026-04.",
    lastUpdated: "2026-05-01",
    maintenanceHistory: [
      { id: "m-901", date: "2026-05-01", type: "flagged", description: "Decommissioned and prepared for public auction.", technician: "Asset Committee" },
    ],
  },
];
